#! /bin/bash

OAUTH_RESPONSE_TYPE=code
OAUTH_CHALLENGE_METHOD=S256
OAUTH_CLIENT_ID="964c8802-eeaa-4e70-8783-6e65d019d7c6"
OAUTH_SCOPE="offline openid"
OAUTH_REDIRECT_URI="http://localhost:1420/auth/callback"
OAUTH_SERVER_BASE_URL="https://oauth2.playtron.red/oauth2"
OAUTH_SERVER_TOKEN_URL="https://oauth2.playtron.red/oauth2/token"
OAUTH_CLIENT_SERVER_PORT=1420
OAUTH_GRANT_TYPE="authorization_code"
PLAYTRON_GAMESCOPE_SESSION=1
CLIENTCMD="grid"
FACTORY_RESET_SENTINEL="/tmp/playtron-factory-reset-sentinel"

if command -v /usr/libexec/playtron/dev-session-trigger > /dev/null; then
	/usr/libexec/playtron/dev-session-trigger &
fi

if lspci | grep -i vga | grep -i nvidia > /dev/null; then
	# required for Nvidia GPUs to work with webview
	# breaks webview for AMD and Intel GPUs
	WEBKIT_DISABLE_DMABUF_RENDERER=1
else
	WEBKIT_DISABLE_DMABUF_RENDERER=0
fi

post_client_shutdown() {
	if [[ -e "$FACTORY_RESET_SENTINEL" ]]; then
		OPTION=$(cat $FACTORY_RESET_SENTINEL)
	        rm -f "$FACTORY_RESET_SENTINEL"
		pkexec playtron-factory-reset $OPTION
	fi
}
